### ISSUE TITLE
Pushing a commit on two branches creates two GradingJobs

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc/classy#364] opened 2021-01-31 04:34 UTC
If a student pushes a commit that's on two branches, it invokes autotest twice _at the same time_
This can happen when a student does a git merge on their local machine with commits not on the origin yet.
I assume it's creating two push events?

The problem is that the grading jobs interfere with each other if they are executing at the same time :(

**Comment by rtholmes** [comment] 2022-09-23 18:50
I think this is fixed in PR #410 , when confirmed this can be closed

**Comment by rtholmes** [comment] 2022-11-03 17:01
@braxtonhall I though this was fixed, but it turns out it is not. 

Our checking code does confirm that a commit is not executing by it's URL, not SHA:

```typescript
if (execution.target.commitURL === input.target.commitURL &&
    execution.target.delivId === input.target.delivId) {
```

For cases when this is happening, could it be the case that this identical SHA has two `commitURL`s because they are on different branches? The question then becomes which one to listen to, since we use the `commitURL` to know where to post back results...

**Comment by rtholmes** [comment] 2022-11-30 22:52
Still happening: if feedback is made on a branch, and it is committed to main without any other changes being made to main, the SHA on main will be the same as the branch and the branch feedback will continue to be given.

Does not happen often, because usually things happen to main between branch commits, but shows up (especially) for single-commit quick changes on branches that are immediately merged.

**Comment by rtholmes** [comment] 2022-12-02 17:29
Here are two push records from mongo w/ the same sha but different branches demonstrating the challenge:

```
{
    "_id" : ObjectId("638924645315f1d76affc5c2"),
    "delivId" : "c3",
    "repoId" : "project_team153",
    "orgId" : "CPSC310-2022W-T1",
    "botMentioned" : false,
    "adminRequest" : false,
    "personId" : "HIDDEN",
    "kind" : "push",
    "cloneURL" : "https://github.students.cs.ubc.ca/CPSC310-2022W-T1/project_team153.git",
    "commitSHA" : "0c9e0c639de2404f76c1ef6079b8eab037b028b0",
    "commitURL" : "https://github.students.cs.ubc.ca/CPSC310-2022W-T1/project_team153/commit/0c9e0c639de2404f76c1ef6079b8eab037b028b0",
    "postbackURL" : "https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2022W-T1/project_team153/commits/0c9e0c639de2404f76c1ef6079b8eab037b028b0/comments",
    "timestamp" : 1669932131927.0,
    "ref" : "refs/heads/main"
}


{
    "_id" : ObjectId("63892d895315f1607cffc5e3"),
    "delivId" : "c3",
    "repoId" : "project_team153",
    "orgId" : "CPSC310-2022W-T1",
    "botMentioned" : false,
    "adminRequest" : false,
    "personId" : "HIDDEN",
    "kind" : "push",
    "cloneURL" : "https://github.students.cs.ubc.ca/CPSC310-2022W-T1/project_team153.git",
    "commitSHA" : "0c9e0c639de2404f76c1ef6079b8eab037b028b0",
    "commitURL" : "https://github.students.cs.ubc.ca/CPSC310-2022W-T1/project_team153/commit/0c9e0c639de2404f76c1ef6079b8eab037b028b0",
    "postbackURL" : "https://github.students.cs.ubc.ca/api/v3/repos/CPSC310-2022W-T1/project_team153/commits/0c9e0c639de2404f76c1ef6079b8eab037b028b0/comments",
    "timestamp" : 1669934473660.0,
    "ref" : "refs/heads/HIDDEN"
}
```

**Comment by rtholmes** [comment] 2022-12-02 23:33
Not just on main: two different branches with the same SHA:
```
autotest  | <I> 12/2/2022, 11:02:18 PM: GitHubAutoTest::handlePushEvent(..) - repo: project_team163; person: TBD; SHA: f89aa4; branch: refs/heads/frontend
autotest  | <I> 12/2/2022, 11:04:46 PM: GitHubAutoTest::handlePushEvent(..) - repo: project_team163; person: TBD; SHA: f89aa4; branch: refs/heads/youtube-link
```

**Comment by rtholmes** [comment] 2024-02-22 19:52
This has been handled by the queue improvements made in [ubccpsc310/classy/pulls/99](https://github.com/ubccpsc310/classy/pull/99)

**Closed by rtholmes** 2024-02-22 19:52 UTC
