### ISSUE TITLE
Confirm correct timestamp when choosing grade

### ISSUE THREAD

**Issue by nickbradley** [ubccpsc/classy#220] opened 2019-01-30 23:30 UTC
A student made a commit 4 minutes before the deadline (https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T2/d0_k2r1b/commit/b89769294865078bb5866ea85feb4efb8199d376) but a grade from a previous commit (https://github.ugrad.cs.ubc.ca/CPSC310-2018W-T2/d0_k2r1b/commit/c645525afae9d8b55698ad732186b3c574f07af3) was released. Unknown when the commit was actually pushed.

**Comment by rtholmes** [comment] 2019-02-04 18:34
@nickbradley : this is what happened. `b8976` was pushed after the deadline (20:01), so it was not counted. While the commit might have been made before the deadline (the commit timestamp is actually 19:56), this cannot be guaranteed because commit timestamps can be faked client side, so we only trust the push date.

**Comment by rtholmes** [comment] 2019-06-06 00:10
`wontfix` because this is by design, even though it feels unsatisfying.

**Closed by rtholmes** 2019-06-06 00:10 UTC
Labels: wontfix
